export const zhAcademicDict: string[] = [
  '人工智能', '机器学习', '深度学习', '神经网络', '强化学习',
  '自然语言处理', '计算机视觉', '图像识别', '目标检测', '图像分割',
  '语音识别', '推荐系统', '知识图谱', '数据挖掘', '模式识别',
  '迁移学习', '联邦学习', '多模态学习', '自监督学习', '弱监督学习',
  '半监督学习', '主动学习', '集成学习', '表示学习', '度量学习',
  '生成对抗网络', '卷积神经网络', '循环神经网络', '图神经网络', '注意力机制',
  'Transformer', 'BERT', 'GPT', '扩散模型', '大语言模型',
  '数字孪生', '边缘计算', '云计算', '物联网', '区块链',
  '元宇宙', '虚拟现实', '增强现实', '混合现实', '扩展现实',
  '无人系统', '自动驾驶', '无人机', '机器人', '智能控制',
  '信号处理', '图像处理', '视频处理', '音频处理', '多媒体',
  '社交网络', '信息检索', '搜索引擎', '文本挖掘', '情感分析',
  '生物信息', '计算生物', '医学影像', '药物发现', '基因编辑',
  '网络安全', '隐私保护', '加密算法', '入侵检测', '恶意软件',
  '软件工程', '需求工程', '程序分析', '软件测试', '软件架构',
  '操作系统', '分布式系统', '数据库', '存储系统', '编译器',
  '优化算法', '演化计算', '群体智能', '约束求解', '近似算法',
  '控制系统', '电力系统', '通信系统', '传感器', '自动化',
  '流体力学', '有限元分析', '计算流体', '结构优化', '多物理场',
  '定量分析', '回归分析', '因子分析', '聚类分析', '时间序列',
  '流行病学', '临床医学', '病理学', '药理学', '基因组学',
  '蛋白质结构', '分子动力学', '细胞生物学', '系统生物学', '合成生物学',
  '社会网络', '计量经济', '行为经济', '实验设计', '调查研究',
]

export const zhAcademicEnMap: Record<string, string> = {
  '人工智能': 'artificial intelligence',
  '机器学习': 'machine learning',
  '深度学习': 'deep learning',
  '神经网络': 'neural network',
  '强化学习': 'reinforcement learning',
  '自然语言处理': 'natural language processing',
  '计算机视觉': 'computer vision',
  '图像识别': 'image recognition',
  '目标检测': 'object detection',
  '图像分割': 'image segmentation',
  '语音识别': 'speech recognition',
  '推荐系统': 'recommender system',
  '知识图谱': 'knowledge graph',
  '数据挖掘': 'data mining',
  '迁移学习': 'transfer learning',
  '联邦学习': 'federated learning',
  '数字孪生': 'digital twin',
  '边缘计算': 'edge computing',
  '云计算': 'cloud computing',
  '物联网': 'internet of things',
  '区块链': 'blockchain',
  '自动驾驶': 'autonomous driving',
  '无人机': 'UAV drone',
  '大语言模型': 'large language model',
  '生成对抗网络': 'generative adversarial network',
  '注意力机制': 'attention mechanism',
  '图神经网络': 'graph neural network',
  '卷积神经网络': 'convolutional neural network',
  '循环神经网络': 'recurrent neural network',
  '计算机': 'computer',
  '医学': 'medical',
  '工程': 'engineering',
  '信息': 'information',
  '系统': 'system',
  '数据': 'data',
  '算法': 'algorithm',
  '模型': 'model',
  '方法': 'method',
  '网络': 'network',
  '检测': 'detection',
  '识别': 'recognition',
  '分析': 'analysis',
  '优化': 'optimization',
  '控制': 'control',
  '设计': 'design',
  '评估': 'evaluation',
  '预测': 'prediction',
  '分类': 'classification',
  '聚类': 'clustering',
  '回归': 'regression',
  '训练': 'training',
  '学习': 'learning',
  '深度': 'deep',
}

export const medicalTerms = [
  '医学', '疾病', '药物', '蛋白', '基因', '癌', '肿瘤',
  '病毒', '细菌', '治疗', '临床', '病理', '细胞',
  'protein', 'gene', 'cancer', 'tumor', 'virus', 'bacteria',
  'treatment', 'therapy', 'clinical', 'disease', 'drug', 'genome',
  'epidemiology', 'pathology', 'pharmacology', 'molecular',
]
